### ISSUE TITLE
A few small points

### ISSUE THREAD

**Issue by abrolag** [jplloyd/yoshimi_website_test#1]
In 'History' the first paragraph should be made into a quote - it was Jonathan Brickman who penned that.

The main window in the images is slightly out of date. There is a new checkbox for system effects.

I would like the first time this goes official to be with Version 1.6.0 release, so version numbers will need correcting.

**Comment by jplloyd** [comment]
I have updated the screenshots using the latest build. Haven't updated the front page image, but that's a quick fix.

The quote is now marked as such, with attribution, and I've updated the version numbers to match the coming release.

Pastramified updates of this have been pushed. Be aware that I will force-push rebases on the alt_style branch for an easier clean merge later.

I'll close this when I've updated the front page image, unless you've found some other issues by then.

**Comment by jplloyd** [comment]
Alright, everything dealt with as of 3901ebb37dc6df7441dd0d5507e0b3ca036b8c72
